<?php


/**
 * Defining the Constants
 */
define('NODE_APPROVAL_NAME', 'node_approval');
define('NODE_APPROVAL_BASE_TABLE', 'node_approval');

define('APPROVE_REAL_LIFE_STORIES_CONTENT','approve real life stories content');
define('APPROVE_VIDEO_LIBRARY','approve library content');
define('APPROVE_RESOURCES','approve resources content');
define('APPROVE_FAQ','approve FAQ content');
define('APPROVE_BLOG','approve blog content');
define('APPROVE_EVENTS','approve events content');
define('APPROVE_CAREERS','approve careers content');
define('APPROVE_LINKS','approve links content');
define('APPROVE_LOCATIONS','approve locations content');
define('APPROVE_GALLERY','approve gallery content');
define('APPROVE_MISCELLANEOUS','approve miscellaneous content');